---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: product-catalog-secrets
  namespace: shopping-cart-apps
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/instance: product-catalog-secrets
    app.kubernetes.io/component: credentials
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: product-catalog-secrets
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: secret/data/postgres/products
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/postgres/products
        property: password
    - secretKey: RABBITMQ_USERNAME
      remoteRef:
        key: secret/data/rabbitmq/default
        property: username
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: secret/data/rabbitmq/default
        property: password
