---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: product-catalog

namespace: shopping-cart-apps

labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize
  includeSelectors: false
- pairs:
    app.kubernetes.io/name: product-catalog
    app.kubernetes.io/part-of: shopping-cart
  includeSelectors: true

resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- seed-job-configmap.yaml
- seed-job.yaml
- fts-index-job.yaml

configMapGenerator:
- name: product-catalog-config
  options:
    labels:
      app.kubernetes.io/component: backend
  envs:
  - configmap.env

images:
  - name: shopping-cart-product-catalog
    newName: ghcr.io/wilddog64/shopping-cart-product-catalog
    newTag: sha-28955c89245d82111f2e0801723b49fe32cee730
