---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-catalog
  namespace: shopping-cart-apps
  labels:
    app.kubernetes.io/name: product-catalog
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: shopping-cart
  annotations:
    # Vault integration - allows service to authenticate with Vault
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "product-catalog"
